export function A(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function B(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function C(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function D(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function E(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function F(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function G(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function H(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function I(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={12} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={6}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={18} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function J(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function K(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={7}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function L(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function M(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect y={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={12} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={18} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function N(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect y={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={12} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={24}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={18} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={18}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function O(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function P(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function Q(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function R(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function S(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={9} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={15} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function T(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={12}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={18} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={12} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={12}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function U(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x={3} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={21} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={3}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={9}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={15}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={3}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={21}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function V(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect y={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function W(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x={29}
        y={29}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 29 29)"
        fill="currentColor"
      />
      <rect
        x={5}
        y={29}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 5 29)"
        fill="currentColor"
      />
      <rect
        x={29}
        y={23}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 29 23)"
        fill="currentColor"
      />
      <rect
        x={5}
        y={23}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 5 23)"
        fill="currentColor"
      />
      <rect
        x={29}
        y={17}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 29 17)"
        fill="currentColor"
      />
      <rect
        x={5}
        y={17}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 5 17)"
        fill="currentColor"
      />
      <rect
        x={23}
        y={23}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 23 23)"
        fill="currentColor"
      />
      <rect
        x={11}
        y={23}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 11 23)"
        fill="currentColor"
      />
      <rect
        x={17}
        y={17}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 17 17)"
        fill="currentColor"
      />
      <rect
        x={29}
        y={11}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 29 11)"
        fill="currentColor"
      />
      <rect
        x={5}
        y={11}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 5 11)"
        fill="currentColor"
      />
      <rect
        x={29}
        y={5}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 29 5)"
        fill="currentColor"
      />
      <rect
        x={5}
        y={5}
        width={5}
        height={5}
        rx={0.526316}
        transform="rotate(180 5 5)"
        fill="currentColor"
      />
    </svg>
  )
}

export function X(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={6}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={24} width={5} height={5} rx={0.526316} fill="currentColor" />
    </svg>
  )
}

export function Y(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={6}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
    </svg>
  )
}

export function Z(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      width={29}
      height={29}
      viewBox="0 0 29 29"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={6} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={12} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={18} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect x={24} width={5} height={5} rx={0.526316} fill="currentColor" />
      <rect
        x={24}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={12}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={6}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={12}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={18}
        y={24}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect
        x={6}
        y={18}
        width={5}
        height={5}
        rx={0.526316}
        fill="currentColor"
      />
      <rect y={24} width={5} height={5} rx={0.526316} fill="currentColor" />
    </svg>
  )
}
